CREATE TABLE IF NOT EXISTS test (
  id INT NOT NULL,
  name VARCHAR(30)  NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS channels (
  id INT NOT NULL,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY(id)
);